{{ if default .Values.lapi.persistentVolume.data.enabled true (not .Values.lapi.persistentVolume.data.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-db-pvc
  namespace: {{ .Release.Namespace }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  {{- if .Values.lapi.persistentVolume.data.annotations }}
{{ toYaml .Values.lapi.persistentVolume.data.annotations | indent 4 }}
  {{- end }}
  labels:
    k8s-app: {{ .Release.Name }}
    type: lapi
    version: v1
spec:
  accessModes:
{{ toYaml .Values.lapi.persistentVolume.data.accessModes | indent 4 }}
{{- if .Values.lapi.persistentVolume.data.storageClassName }}
{{- if (eq "-" .Values.lapi.persistentVolume.data.storageClassName) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.lapi.persistentVolume.data.storageClassName }}"
{{- end }}
{{- end }}
  resources:
    requests:
      storage: "{{ .Values.lapi.persistentVolume.data.size }}"
{{ end }}
---
{{ if default .Values.lapi.persistentVolume.config.enabled true (not .Values.lapi.persistentVolume.config.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-config-pvc
  namespace: {{ .Release.Namespace }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  {{- if .Values.lapi.persistentVolume.config.annotations }}
{{ toYaml .Values.lapi.persistentVolume.config.annotations | indent 4 }}
  {{- end }}
  labels:
    k8s-app: {{ .Release.Name }}
    type: lapi
    version: v1
spec:
  accessModes:
{{ toYaml .Values.lapi.persistentVolume.config.accessModes | indent 4 }}
{{- if .Values.lapi.persistentVolume.config.storageClassName }}
{{- if (eq "-" .Values.lapi.persistentVolume.config.storageClassName) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.lapi.persistentVolume.config.storageClassName }}"
{{- end }}
{{- end }}
  resources:
    requests:
      storage: "{{ .Values.lapi.persistentVolume.config.size }}"
{{ end }}